Phase one of addressing exposed passwords.
odoo/docker pull request #497
Opened 2024-04-03 16:27 UTC by lathama

## Phase one of addressing exposed passwords.

- For https://github.com/odoo/docker/issues/334
- Enable users to see what configuration settings they can/should set for databases
- Prepare for excluding the password from the command which is visible from the host machine.

## The problem
```
lathama@hostsystemnotthedockercontainer: $ ps ax | grep '/bin/odoo'
/usr/bin/python3 /usr/bin/odoo --db_host db --db_port 5432 --db_user odoo --db_password odoo
```

## The goal

```
lathama@hostsystemnotthedockercontainer: $ ps ax | grep '/bin/odoo'
/usr/bin/python3 /usr/bin/odoo
```

## Related

- https://github.com/odoo/docker/issues/343
- https://github.com/odoo/docker/issues/302
- https://github.com/odoo/docker/issues/265
- https://github.com/odoo/docker/issues/424

2024-04-03 16:29 UTC, lathama commented
@odony and or @d-fence I will ask for some help getting this going.

2024-04-03 17:12 UTC, amh-mw requested changes
Passing --db-password on the command line is a convenience for local development. There are already multiple mechanisms for doing this more securely.

1. Mount an entire odoo.conf into the container, replacing these defaults and adding your password in the config file.
```yaml
    # docker-compose.yaml
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
```

2. Expose sensitive values as environment variables:
```yaml
    # docker-compose.yaml
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
```

I generally find this pull request without merit and think it should be closed.

2024-04-03 17:12 UTC, amh-mw commented on 15.0/odoo.conf
> +db_name = postgress
[--database](https://www.odoo.com/documentation/15.0/developer/reference/cli.html#cmdoption-odoo-bin-d) > `db_name` setting
> database(s) used when installing or updating modules. Providing a comma-separated list restrict access to databases provided in list.

Setting a default db_name here unexpectedly restricts available databases, breaking current expectations.

2024-04-03 18:00 UTC, lathama commented
Note to viewers, the CLI wins over the config file in some cases like db config. Read more at https://github.com/odoo/odoo/blob/17.0/odoo/tools/config.py#L448-L484

2025-01-16 21:36 UTC, lathama commented
closing for lack of resources

2025-01-16 21:36 UTC, closed without merging